// Mock data for MVP demonstration
export const mockServices = [
  {
    service_id: "svc-001",
    name: "National ID Card",
    name_am: "ብሔራዊ መታወቂያ ካርድ",
    name_or: "Waraqaa Eenyummaa Biyyaalessaa",
    category: "Identity",
    description: "Apply for a new national identification card or renew an existing one.",
    description_am: "አዲስ ብሔራዊ መታወቂያ ካርድ ለማመልከት ወይም ያለውን ለማደስ",
    estimated_processing_time: "5-7 business days",
    service_fee: 150,
    requirements: ["Birth Certificate", "Two passport photos", "Proof of residence"],
    status: "active",
  },
  {
    service_id: "svc-002",
    name: "Birth Certificate",
    name_am: "የልደት ምስክር ወረቀት",
    name_or: "Ragaa Dhaloota",
    category: "Civil Registration",
    description: "Register a birth and obtain an official birth certificate.",
    description_am: "ልደትን መመዝገብ እና ኦፊሴላዊ የልደት ምስክር ወረቀት ማግኘት",
    estimated_processing_time: "3-5 business days",
    service_fee: 50,
    requirements: ["Hospital birth record", "Parent IDs", "Marriage certificate (if applicable)"],
    status: "active",
  },
  {
    service_id: "svc-003",
    name: "Business License",
    name_am: "የንግድ ፍቃድ",
    name_or: "Hayyama Daldalaa",
    category: "Business",
    description: "Apply for a new business license or renew an existing one.",
    description_am: "አዲስ የንግድ ፍቃድ ለማመልከት ወይም ያለውን ለማደስ",
    estimated_processing_time: "10-14 business days",
    service_fee: 500,
    requirements: ["Business plan", "Tax ID", "Proof of address", "Owner ID"],
    status: "active",
  },
  {
    service_id: "svc-004",
    name: "Passport Application",
    name_am: "የፓስፖርት ማመልከቻ",
    name_or: "Iyyannoo Paaspoortii",
    category: "Travel",
    description: "Apply for a new Ethiopian passport or renew an existing one.",
    description_am: "አዲስ የኢትዮጵያ ፓስፖርት ለማመልከት ወይም ያለውን ለማደስ",
    estimated_processing_time: "15-30 business days",
    service_fee: 1500,
    requirements: ["National ID", "Birth Certificate", "Four passport photos", "Proof of payment"],
    status: "active",
  },
  {
    service_id: "svc-005",
    name: "Driver's License",
    name_am: "የመንጃ ፍቃድ",
    name_or: "Hayyama Konkolaataa",
    category: "Transport",
    description: "Apply for a new driver's license or renew an existing one.",
    description_am: "አዲስ የመንጃ ፍቃድ ለማመልከት ወይም ያለውን ለማደስ",
    estimated_processing_time: "7-10 business days",
    service_fee: 300,
    requirements: ["National ID", "Medical certificate", "Driving test certificate", "Two photos"],
    status: "active",
  },
  {
    service_id: "svc-006",
    name: "Marriage Certificate",
    name_am: "የጋብቻ ምስክር ወረቀት",
    name_or: "Ragaa Fuudhaa",
    category: "Civil Registration",
    description: "Register a marriage and obtain an official marriage certificate.",
    description_am: "ጋብቻን መመዝገብ እና ኦፊሴላዊ የጋብቻ ምስክር ወረቀት ማግኘት",
    estimated_processing_time: "1-3 business days",
    service_fee: 100,
    requirements: ["Both parties' IDs", "Birth certificates", "Witnesses IDs", "Medical certificates"],
    status: "active",
  },
  {
    service_id: "svc-007",
    name: "Land Title Registration",
    name_am: "የመሬት ባለቤትነት ምዝገባ",
    name_or: "Galmee Abbaa Qabeenya Lafaa",
    category: "Property",
    description: "Register land ownership and obtain a title deed.",
    description_am: "የመሬት ባለቤትነት መመዝገብ እና የይዞታ ማረጋገጫ ማግኘት",
    estimated_processing_time: "30-45 business days",
    service_fee: 2000,
    requirements: ["Purchase agreement", "Previous title deed", "Survey report", "Tax clearance"],
    status: "active",
  },
  {
    service_id: "svc-008",
    name: "Tax Clearance Certificate",
    name_am: "የታክስ ነፃነት ማረጋገጫ",
    name_or: "Ragaa Qulqullina Gibiraa",
    category: "Tax",
    description: "Obtain a certificate confirming tax compliance.",
    description_am: "የታክስ ክፍያ ማረጋገጫ ምስክር ወረቀት ማግኘት",
    estimated_processing_time: "3-5 business days",
    service_fee: 75,
    requirements: ["Tax ID", "Recent tax returns", "Business license"],
    status: "active",
  },
]

export const mockApplications = [
  {
    application_id: "app-001",
    service_id: "svc-001",
    service_name: "National ID Card",
    user_id: "user-001",
    status: "processing",
    created_at: "2026-01-10T08:30:00Z",
    updated_at: "2026-01-14T14:20:00Z",
    tracking_number: "ETH-2026-00001",
    notes: "Documents verified. ID card being printed.",
  },
  {
    application_id: "app-002",
    service_id: "svc-004",
    service_name: "Passport Application",
    user_id: "user-001",
    status: "submitted",
    created_at: "2026-01-15T10:00:00Z",
    updated_at: "2026-01-15T10:00:00Z",
    tracking_number: "ETH-2026-00002",
    notes: "Awaiting document verification.",
  },
  {
    application_id: "app-003",
    service_id: "svc-002",
    service_name: "Birth Certificate",
    user_id: "user-001",
    status: "approved",
    created_at: "2026-01-05T09:15:00Z",
    updated_at: "2026-01-08T16:45:00Z",
    tracking_number: "ETH-2026-00003",
    notes: "Certificate ready for collection.",
  },
]

export const mockNotifications = [
  {
    id: "notif-001",
    title: "Application Update",
    message: "Your National ID Card application is now being processed.",
    type: "info",
    read: false,
    created_at: "2026-01-14T14:20:00Z",
  },
  {
    id: "notif-002",
    title: "Document Required",
    message: "Please upload additional passport photos for your Passport Application.",
    type: "warning",
    read: false,
    created_at: "2026-01-15T11:00:00Z",
  },
  {
    id: "notif-003",
    title: "Application Approved",
    message: "Your Birth Certificate application has been approved. Ready for collection.",
    type: "success",
    read: true,
    created_at: "2026-01-08T16:45:00Z",
  },
]

export const mockUsers = [
  { id: "user-001", email: "citizen@demo.gov.et", role: "citizen", name: "Abebe Kebede", created_at: "2025-06-15" },
  { id: "user-002", email: "employee@demo.gov.et", role: "employee", name: "Tigist Haile", created_at: "2025-03-20" },
  { id: "user-003", email: "admin@demo.gov.et", role: "admin", name: "Dawit Solomon", created_at: "2025-01-10" },
  { id: "user-004", email: "partner@demo.gov.et", role: "partner", name: "Meron Tadesse", created_at: "2025-08-05" },
]

export const mockStats = {
  totalUsers: 1247893,
  totalServices: 50,
  totalApplications: 3456789,
  pendingApplications: 12456,
  completedApplications: 3444333,
  avgProcessingTime: "4.2 days",
  citizenSatisfaction: 4.6,
  uptime: "99.97%",
}

export const mockFeedback = [
  {
    id: "fb-001",
    rating: 5,
    comment: "Excellent service! Got my ID card in just 5 days.",
    service: "National ID Card",
    user: "Abebe K.",
    date: "2026-01-12",
  },
  {
    id: "fb-002",
    rating: 4,
    comment: "Good experience, but the website could be faster.",
    service: "Birth Certificate",
    user: "Sara M.",
    date: "2026-01-10",
  },
  {
    id: "fb-003",
    rating: 5,
    comment: "Very helpful staff and clear instructions.",
    service: "Business License",
    user: "Dawit T.",
    date: "2026-01-08",
  },
  {
    id: "fb-004",
    rating: 3,
    comment: "Process took longer than expected.",
    service: "Passport Application",
    user: "Meron A.",
    date: "2026-01-05",
  },
]

// Demo credentials
export const demoCredentials = {
  citizen: { email: "citizen@demo.gov.et", password: "demo123" },
  employee: { email: "employee@demo.gov.et", password: "demo123" },
  admin: { email: "admin@demo.gov.et", password: "demo123" },
  partner: { email: "partner@demo.gov.et", password: "demo123" },
}
